# Package

In [62]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [ ]:
# 假定討論年紀與存活率之間的關係

# Create Data

In [58]:
# 創造100個1 和 0
survival = np.concatenate(([1]*100,[0]*100))

In [59]:
# 以 Gamma Distribution 模擬年齡資料
old = np.random.gamma(50,1,100)
young = np.random.gamma(10,1,100)

In [61]:
# 合併數據
age = np.concatenate((young.round(),old.round()))
survival_data = pd.DataFrame({'Survival': survival,'Age': age})

# 切割訓練集

In [64]:
X_train, X_test, y_train, y_test= train_test_split(age, survival, test_size=.2, random_state=82, stratify= None)

In [96]:
# You should reshape your X to be a 2D array not 1D array. Fitting a model requires requires a 2D array.
X_train = X_train.reshape(-1,1)
X_test = X_test.reshape(-1,1)

# 模型訓練

In [97]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [98]:
model.intercept_

array([14.9021751])

In [99]:
model.coef_

array([[-0.55838689]])

In [100]:
model.predict_proba(X_test)

array([[5.13551940e-05, 9.99948645e-01],
       [9.99999584e-01, 4.16104125e-07],
       [9.99993212e-01, 6.78767394e-06],
       [9.99993212e-01, 6.78767394e-06],
       [5.13551940e-05, 9.99948645e-01],
       [9.99999998e-01, 1.56371919e-09],
       [2.93825560e-05, 9.99970617e-01],
       [2.74157813e-04, 9.99725842e-01],
       [5.13551940e-05, 9.99948645e-01],
       [9.99988136e-01, 1.18637807e-05],
       [8.37075646e-04, 9.99162924e-01],
       [9.99998729e-01, 1.27118962e-06],
       [8.97577667e-05, 9.99910242e-01],
       [8.97577667e-05, 9.99910242e-01],
       [9.99988136e-01, 1.18637807e-05],
       [9.99998729e-01, 1.27118962e-06],
       [1.46216796e-03, 9.98537832e-01],
       [9.99999762e-01, 2.38066208e-07],
       [5.13551940e-05, 9.99948645e-01],
       [5.13551940e-05, 9.99948645e-01],
       [2.55285985e-03, 9.97447140e-01],
       [9.96852956e-01, 3.14704390e-03],
       [1.68108893e-05, 9.99983189e-01],
       [9.98967680e-01, 1.03232026e-03],
       [9.999637

In [101]:
 model.score(X_test, y_test)

1.0